name: Golang Backend

on:
  workflow_call:
    inputs:
      go_version:
        type: string
        required: false
        default: ">=1.22.0"
      work_dir:
        type: string
        required: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.work_dir }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          cache-dependency-path: ${{ inputs.work_dir }}/go.sum
          go-version: ${{ inputs.go_version }}


      - name: Vet
        run: go vet ./...

      - name: Vulnerabilities
        uses: golang/govulncheck-action@v1
        with:
          check-latest: true
          go-package: ./...
          go-version-input: ${{ inputs.go_version }}
          repo-checkout: false
          work-dir: ${{ inputs.work_dir }}

      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          only-new-issues: true
          version: latest
          working-directory: ${{ inputs.work_dir }}

      - name: Tests
        uses: robherley/go-test-action@v0
        with:
          moduleDirectory: ${{ inputs.work_dir }}
          testArguments: -vet=off -race ./...
