name: Golang Backend

on:
  workflow_call:
    inputs:
      go_version: 
        type: string
        required: false
        default: ">=1.22.0"
      work_dir:
        type: string
        required: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{inputs.go_version}}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Go Vet
        shell: bash
        working-directory: ${{inputs.work_dir}}
        run: go vet ./...

      - name: Check for vulnerabilities
        id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
          go-package: ./...
          work-dir: ${{inputs.work_dir}}
          check-latest: true

      - name: Run Linter
        shell: bash
        working-directory: ${{inputs.work_dir}}
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin
          golangci-lint run --out-format=github-actions

      - name: Run Tests
        shell: bash
        working-directory: ${{inputs.work_dir}}
        run: go test -short -vet=off -failfast -race -v -coverprofile=coverage.out ./...